name: 'A Beer Tourist: Beer Food Lodging'
favicon: null
layout_spectrum: 0.8
typography_spectrum: 0.74111
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#009343'
    - '#a7dabe'
    - '#6fc294'
    - '#2fa765'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose:
  - name: follow
    item: null
    url: null
